pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t movie-api ./MovieApp'
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                docker stop movie-container >nul 2>&1
                docker rm movie-container >nul 2>&1
                docker run -d -p 7000:7000 --name movie-container movie-api
                '''
            }
        }

        stage('Verify Container') {
            steps {
                bat 'docker ps'
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}

