pipeline {
    agent any

    environment {
        IMAGE_NAME = "movie-api"
        CONTAINER_NAME = "movie-api"
        PORT = "5000"
    }

    stages {
        stage('Checkout') {
            steps {
                // Pull your repo code
                git 'https://github.com/BorraTriveni123/POC.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove existing container if running
                    sh """
                        if [ \$(docker ps -aq -f name=${CONTAINER_NAME}) ]; then
                            docker rm -f ${CONTAINER_NAME}
                        fi
                    """

                    // Run the container
                    sh "docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} ${IMAGE_NAME}"
                }
            }
        }

        stage('Verify Container') {
            steps {
                // List running containers
                sh "docker ps"
            }
        }
    }

    post {
        success {
            echo "Movie API container is up and running on port ${PORT}"
        }
        failure {
            echo "Pipeline failed. Check logs."
        }
    }
}
